comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true

- name: Upload coverage reports to Codecov
  uses: codecov/codecov-action@v4.0.1
  env:
    token: ${{ secrets.CODECOV_TOKEN }}
    slug: ericmshearer/OCepi

language: R

sudo: false

cache: packages

after_success:

- Rscript -e 'covr::codecov()'
